// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBpBW1xk3GqqLsBtqeGGHx7Zcli-teeb0s',
    appId: '1:466263678460:android:d8af83f45773eb24bee679',
    messagingSenderId: '466263678460',
    projectId: 'alquilamelo-app',
    storageBucket: 'alquilamelo-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_hglfJ04691SNofetlsrcEU50-vKuQ1g',
    appId: '1:466263678460:ios:13a72bdf4f8e60debee679',
    messagingSenderId: '466263678460',
    projectId: 'alquilamelo-app',
    storageBucket: 'alquilamelo-app.firebasestorage.app',
    iosBundleId: 'com.example.alquilameloApp',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPEDQQt9Zj_odSpReJ6OLWnWeT9dE890M',
    appId: '1:466263678460:web:4863b7e8b399b0e4bee679',
    messagingSenderId: '466263678460',
    projectId: 'alquilamelo-app',
    authDomain: 'alquilamelo-app.firebaseapp.com',
    storageBucket: 'alquilamelo-app.firebasestorage.app',
  );

}